server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://<REMOTE_HOST>:3306/<DB_NAME>?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: <USERNAME>
    password: <PASSWORD>
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 4
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update   # 首次运行可自动建表；若你们远端库已建表，改为 validate 更安全
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: Asia/Shanghai
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
